#include<iostream>
#include <fstream>
using namespace std;

class DocWriter{
public:
	DocWriter();
	DocWriter(const string& fileName, const string&content);
	~DocWriter();
	// 파일 이름을 지정 
	void SetFileName(const string& fileName);

	// 저장할 텍스트를 지정 
	void SetContent(const string& content);

	// 파일에 텍스트를 저장시킨다. 
	void Write();

protected:
	string _fileName;
	string _content;
};

DocWriter::DocWriter(){
	cout << "DocWriter 디폴트 생성자" << endl;
	_fileName = "NoName.txt";
	_content = "There is no content.";
}
DocWriter::DocWriter(const string& fileName, const string&content){
	cout << "DocWriter 인자가 있는 생성자" << endl;
	_fileName = fileName;
	_content = content;
}
DocWriter::~DocWriter(){
	cout << "DocWriter 소멸자" << endl;
}

void DocWriter::SetFileName(const string& fileName){
	_fileName = fileName;
}
void DocWriter::SetContent(const string& content){
	_content = content;
}
void DocWriter::Write(){
	ofstream of(_fileName.c_str()); //file open
	of << "# Content #" << endl << endl; //header cout
	of << _content.c_str(); // 
}
///////////////////////////////////////////////////////////////////////////////////
class HTMLWriter :public DocWriter{
public:
	HTMLWriter();
	HTMLWriter(const string& fileName, const string&content);
	~HTMLWriter();
	// 텍스트를 파일로 저장시킨다.
	void Write();

	// 폰트를 지정한다. 
	void SetFont(const string& fontName, int fontSize, const string& fontColor);
protected:
	string _fontName;
	int _fontSize;
	string _fontColor;
};

HTMLWriter::HTMLWriter(const string& fileName, const string&content)
	:DocWriter(fileName, content)
{
	cout << "HTMLWriter의 인자가 있는 생성자" << endl;
}
HTMLWriter::HTMLWriter(){
	cout << "HTMLWriter 디폴트 생성자" << endl;
	// 디폴트 파일 이름만 바꾼다.
	_fileName = "Noname.html";
	// 디폴트 폰트를 지정한다.
	_fontName = "굴림";
	_fontSize = 3;
	_fontColor = "black";
}
HTMLWriter::~HTMLWriter(){
	cout << "HTMLWriter 소멸자" << endl;
}
// 텍스트를 파일로 저장시킨다.
void HTMLWriter::Write(){
	ofstream of(_fileName.c_str());
	// HTML 헤더 부분을 저장한다. 
	of << "<HTML><HEAD><TITLE>This document was generated by HTMLWriter</TITLE></HEAD><BODY>";
	of << "<H1>Content</H1>";
	// 폰트 태그를 시작한다. 
	of << "<Font name='" << _fontName.c_str() << "' size='" << _fontSize << "' color='" << _fontColor.c_str() << "'>";
	// 텍스트를 저장한다. 
	of << _content.c_str();
	// 폰트 태그를 닫는다.
	of << "</FONT>";
	// HTML을 마무리 한다. 
	of << "</BODY></HTML>";
}

// 폰트를 지정한다. 
void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor){
	_fontName = fontName;
	_fontSize = fontSize;
	_fontColor = fontColor;
}

int main(){

	/**/
	HTMLWriter doc1("test1.html", "Run To You 1!!"); //자식 객체
	HTMLWriter doc2("test2.html", "Run To You 2!!");
	HTMLWriter doc3("test3.html", "Run To You 3!!");

	DocWriter doc;
	doc = doc1;
	doc.Write();

	DocWriter* pDoc = &doc2;  //포인터 객체
	pDoc->Write();

	DocWriter& rDoc = doc3; //레퍼런스 객체
	rDoc.Write();

	return 0;
}
